import {
    View,
    Text,
    TextInput,
    FlatList,
    TouchableOpacity,
    Keyboard,
    TouchableWithoutFeedback,
    KeyboardAvoidingView,
    Platform,
} from "react-native";
import React, { useEffect, useRef, useState } from "react";
import { Send } from "lucide-react-native";
import { COLORS } from "@/src/consts/colors";
import { useHeaderHeight } from "@react-navigation/elements";
import ScreenWrapper from "../../components/ScreenWrapper";

type MessageTypes = {
    text: string;
    role: "model" | "user";
    timestamp: number;
};

const dummyResponses = [
    "🤖 DUMMY RESPONSE: AI is currently on coffee break.",
    "PLACEHOLDER TEXT — this is not a real answer.",
    "Fake AI says hello 👋 (replace with real output)",
    "🚧 Dummy response ahead. Nothing smart here.",
    "This response was generated by absolutely nothing.",
    "Pretend this is something insightful. It is not.",
    "Mock AI output — for testing purposes only.",
    "⚠️ Dummy data detected. Real AI not connected.",
    "Lorem ipsum, but make it AI. (Still fake.)",
    "If you're reading this, the AI failed gracefully 😅",
];

export default function Chats() {
    const [messages, setMessages] = useState<MessageTypes[]>([]);
    const [text, setText] = useState("");
    const headerHeight = useHeaderHeight();
    const scrollRef = useRef<FlatList<MessageTypes>>(null);

    const handleSend = () => {
        if (!text.trim()) return;

        const userMsg: MessageTypes = {
            role: "user",
            text: text,
            timestamp: Date.now(),
        };

        setMessages((prev) => [...prev, userMsg]);

        const modelMsg: MessageTypes = {
            role: "model",
            text: dummyResponses[
                Math.floor(Math.random() * dummyResponses.length)
            ],
            timestamp: Date.now(),
        };

        setMessages((prev) => [...prev, modelMsg]);

        setText("");
    };

    useEffect(() => {
        const timeout = setTimeout(() => {
            scrollRef.current?.scrollToEnd({ animated: true });
        }, 50);

        return () => clearTimeout(timeout);
    }, [messages]);

    return (
        <ScreenWrapper>
            <KeyboardAvoidingView
                style={{ flex: 1 }}
                className="bg-background"
                behavior="padding"
                keyboardVerticalOffset={
                    Platform.OS === "ios" ? 90 : headerHeight
                }
            >
                <View className="flex-1 border ">
                    <View className="flex-1 bg-background">
                        {/* Messages */}
                        <FlatList
                            ref={scrollRef}
                            data={messages}
                            keyExtractor={(item, index) =>
                                item.timestamp.toString() + index
                            }
                            scrollEnabled={true}
                            contentContainerClassName="p-4"
                            keyboardShouldPersistTaps="handled"
                            ListEmptyComponent={
                                <Text className="text-text-secondary text-center mt-10">
                                    No messages yet
                                </Text>
                            }
                            renderItem={({ item }) => (
                                <View
                                    className={`mb-2 ${
                                        item.role === "user"
                                            ? "items-end"
                                            : "items-start"
                                    }`}
                                >
                                    <View className="bg-surface px-4 py-2 rounded-xl max-w-[80%]">
                                        <Text className="text-gray-300">
                                            {item.text}
                                        </Text>
                                    </View>
                                </View>
                            )}
                        />

                        {/* Input */}
                        <View className="flex-row gap-2 py-2 items-center">
                            <TextInput
                                value={text}
                                onChangeText={setText}
                                className="flex-1 text-lg bg-surface rounded-xl text-gray-100 px-4 py-3"
                                placeholder="Enter message"
                                placeholderTextColor={COLORS.textSecondary}
                                returnKeyType="send"
                                onSubmitEditing={handleSend}
                            />

                            <TouchableOpacity
                                onPress={handleSend}
                                className="p-3 bg-primary-dark rounded-full items-center justify-center"
                            >
                                <Send color="white" size={20} />
                            </TouchableOpacity>
                        </View>
                    </View>
                </View>
            </KeyboardAvoidingView>
        </ScreenWrapper>
    );
}
